---
- name: Install and configure Zabbix Agent on Linux
  hosts: all
  become: true

  vars:
    zabbix_server_ip: "172.28.4.58" # IP de tu Zabbix Proxy (VM3)
    zabbix_agent_hostname: "{{ inventory_hostname }}" # Usa el hostname del inventario

  tasks:
    # Añadir esta pausa ANTES de que Ansible intente sudo por primera vez
    - name: Wait for server to be ready for sudo
      ansible.builtin.pause:
        seconds: 3 # Ajusta el tiempo según sea necesario, más de 2 segundos.
      when: ansible_facts['distribution_major_version'] == "9" # Solo para CentOS 9 que tiene el problema de sudo password
                                                              # No para 172.28.4.47 (CentOS 7) porque falla en el SSH login

    - name: Ensure Zabbix GPG key is imported  # <--- Indentación corregida aquí (4 espacios desde el margen)
      ansible.builtin.rpm_key:
        state: present
        key: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX

    # Tareas condicionales para añadir el repositorio Zabbix según la versión de CentOS
    # Para CentOS 9 (Enterprise Linux 9) - Zabbix 7.0
    - name: Add Zabbix 7.0 repository for EL9
      ansible.builtin.yum_repository:
        name: zabbix
        description: Zabbix Official Repository - 7.0 for EL9
        baseurl: https://repo.zabbix.com/zabbix/7.0/rhel/9/x86_64/
        gpgcheck: yes
        gpgkey: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX
        enabled: yes
        sslverify: yes
        state: present
      when: ansible_facts['distribution_major_version'] == "9"

    # Para CentOS 7 (Enterprise Linux 7) - Zabbix 6.0 LTS
    - name: Add Zabbix 6.0 LTS repository for EL7
      ansible.builtin.yum_repository:
        name: zabbix
        description: Zabbix Official Repository - 6.0 LTS for EL7
        baseurl: https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/
        gpgcheck: yes
        gpgkey: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX
        enabled: yes
        sslverify: yes
        state: present
      when: ansible_facts['distribution_major_version'] == "7"

    # Tarea para deshabilitar el repositorio frontend (si está presente)
    - name: Disable Zabbix frontend repo (if present)
      ansible.builtin.ini_file:
        path: /etc/yum.repos.d/zabbix.repo
        section: zabbix-frontend
        option: enabled
        value: '0'
        backup: yes
      ignore_errors: yes # Ignorar si la sección no existe

    # Tarea para instalar el agente Zabbix (el nombre del paquete es el mismo)
    - name: Install Zabbix agent
      ansible.builtin.yum:
        name: zabbix-agent
        state: present

    # Tareas para configurar el agente Zabbix
    - name: Configure Zabbix agent (zabbix_agentd.conf - Server/ServerActive)
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: "^(Server|ServerActive)="
        line: "Server={{ zabbix_server_ip }}\nServerActive={{ zabbix_server_ip }}:10051"
        state: present
        backup: yes
      notify: Restart zabbix-agent

    - name: Configure Hostname in zabbix_agentd.conf
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: "^Hostname="
        line: "Hostname={{ zabbix_agent_hostname }}"
        state: present
        backup: yes
      notify: Restart zabbix-agent

    # Tarea para abrir el puerto del agente Zabbix en firewalld
    - name: Open Zabbix agent port in firewalld
      ansible.posix.firewalld:
        port: 10050/tcp
        permanent: true
        state: enabled
        immediate: true

    # Tarea para iniciar y habilitar el servicio del agente Zabbix
    - name: Start and enable Zabbix agent service
      ansible.builtin.systemd:
        name: zabbix-agent
        state: started
        enabled: true

  handlers:
    - name: Restart zabbix-agent
      ansible.builtin.systemd:
        name: zabbix-agent
        state: restarted