---
- name: Install and configure Zabbix Agent on Linux
  hosts: all
  become: true # Esto ejecuta las tareas con privilegios de root (sudo)

  vars:
    zabbix_server_ip: "172.28.4.58" # IP de tu Zabbix Proxy (VM3)
    zabbix_agent_hostname: "{{ inventory_hostname }}" # Usa el hostname del inventario

  tasks:
    - name: Install Zabbix agent repository
      ansible.builtin.yum:
        name: "https://repo.zabbix.com/zabbix/7.0/centos/9/x86_64/zabbix-web-service-7.0.14-release1.el9.x86_64.rpm" # O la URL para Zabbix 7.0

        state: present

    - name: Disable Zabbix frontend repo (if present)
      ansible.builtin.ini_file:
        path: /etc/yum.repos.d/zabbix.repo
        section: zabbix-frontend
        option: enabled
        value: '0'
        backup: yes
      ignore_errors: yes # Ignorar si no existe la sección

    - name: Install Zabbix agent
      ansible.builtin.yum:
        name: zabbix-agent
        state: present

    - name: Configure Zabbix agent (zabbix_agentd.conf)
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: "^(Server|ServerActive)="
        line: "Server={{ zabbix_server_ip }}\nServerActive={{ zabbix_server_ip }}:10051"
        state: present
        backup: yes
      notify: Restart zabbix-agent

    - name: Configure Hostname in zabbix_agentd.conf
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: "^Hostname="
        line: "Hostname={{ zabbix_agent_hostname }}"
        state: present
        backup: yes
      notify: Restart zabbix-agent

    - name: Open Zabbix agent port in firewalld
      ansible.posix.firewalld:
        port: 10050/tcp
        permanent: true
        state: enabled
        immediate: true

    - name: Start and enable Zabbix agent service
      ansible.builtin.systemd:
        name: zabbix-agent
        state: started
        enabled: true

  handlers:
    - name: Restart zabbix-agent
      ansible.builtin.systemd:
        name: zabbix-agent
        state: restarted